### ISSUE TITLE
Notice 컴포넌트 제작

### ISSUE THREAD

**Issue by seola1ne** [gimhanul/Gati-app#7]
### ✨ Describe

알림 아이콘을 눌렀을 때, 모인 알림을 볼 수 있는 Notice 컴포넌트를 만들어야 합니다. 

### ✅ Tasks

- [ ] Notice.js 파일 생성
- [ ] 아이콘 눌렀을 때 화면 넘어가는 기능 구현
- [ ] 쌓인 알림 볼 수 있는 기능 구현
